cases/urls.py
from django.urls import path
from cases.views import (
    CasesListView, create_case, CaseDetailView, update_case, RemoveCaseView,
    CloseCaseView, select_contact, GetCasesView, AddCommentView,
    UpdateCommentView, DeleteCommentView,
    AddAttachmentView, DeleteAttachmentsView)

app_name = 'cases'

urlpatterns = [
    path('', CasesListView.as_view(), name='list'),
    path('create/', create_case, name='add_case'),
    path('<int:pk>/view/', CaseDetailView.as_view(), name="view_case"),
    path('<int:pk>/edit_case/', update_case, name="edit_case"),
    path('<int:case_id>/remove/',
         RemoveCaseView.as_view(), name="remove_case"),

    path('close_case/', CloseCaseView.as_view(), name="close_case"),
    path('select_contacts/', select_contact, name="select_contacts"),
    path('get/list/', GetCasesView.as_view(), name="get_cases"),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/',
         DeleteCommentView.as_view(), name="remove_comment"),

    path('attachment/add/',
         AddAttachmentView.as_view(), name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
]

common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login, create_lead_from_site,
    activate_user, resend_activation_link
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),
    path('create-lead-from-site/', create_lead_from_site,
         name='create_lead_from_site'),

    # user activate link
    path('activate-user/<uidb64>/<token>/<activation_key>/', activate_user, name='activate_user'),
    path('resend_activation_link/<userId>/', resend_activation_link, name='resend_activation_link'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/',
         include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('invoices/', include('invoices.urls', namespace="invoices")),
    path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

events/urls.py
from django.urls import path
from events.views import *

app_name = 'events'


urlpatterns = [
    path('', events_list, name='events_list'),
    path('create/', event_create, name='event_create'),
    path('detail/<int:event_id>/', event_detail_view, name='detail_view'),
    path('edit/<int:event_id>/', event_update, name='event_update'),
    path('delete/<int:event_id>/', event_delete, name='event_delete'),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),

    path('attachment/add/', AddAttachmentView.as_view(), name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
]

marketing/urls.py
from django.urls import path, include
from .views import (
    dashboard, contact_lists, contacts_list, contact_list_new, contact_list_detail, edit_contact,
    email_template_list, email_template_new, email_template_edit, email_template_delete,
    email_template_detail, campaign_list, campaign_new, campaign_details, campaign_delete,
    edit_contact_list, failed_contact_list_download_delete,
    campaign_link_click, campaign_open, demo_file_download, delete_contact, unsubscribe_from_campaign, contact_detail,
    download_contacts_for_campaign, create_campaign_from_template,
    download_links_clicked, delete_multiple_contacts, download_failed_contacts, delete_all_contacts,
    add_email_for_campaigns, list_all_emails_for_campaigns, edit_email_for_campaigns, delete_email_for_campaigns,
    add_blocked_domain, blocked_domain_list, edit_blocked_domain, delete_blocked_domain,
    add_blocked_email, blocked_email_list, edit_blocked_email, delete_blocked_email,
    contacts_list_elastic_search,
    # MarketingContactEmailSearch,
    # contacts_list_new
    # delete_contact_list
    # campaign_edit
    # edit_failed_contact
    # delete_failed_contact
    # failed_contact_list_detail
)

app_name = 'marketing'

urlpatterns = [
    path('', dashboard, name='dashboard'),

    path('contact-list/', contact_lists, name='contact_lists'),
    path('contacts/<int:pk>/edit/', edit_contact, name='edit_contact'),
    path('contacts/<int:pk>/delete/', delete_contact, name='delete_contact'),
    path('contacts/', contacts_list_elastic_search, name='contacts_list'),
    path('contact-list/create/', contact_list_new, name='contact_list_new'),
    # path('cl/list/cnew/', contacts_list_new, name='contacts_list_new'),
    path('contact-list/<int:pk>/detail/', contact_list_detail, name='contact_list_detail'),
    # path('contact-list/<int:pk>/failed/', failed_contact_list_detail, name='failed_contact_list_detail'),
    # path('contact-list/<int:pk>/failed/edit/', edit_failed_contact, name='edit_failed_contact'),
    # path('contact-list/<int:pk>/failed/delete/', delete_failed_contact, name='delete_failed_contact'),
    path('contact-list/<int:pk>/failed/download/',
         failed_contact_list_download_delete, name='failed_contact_list_download_delete'),
    path('contact-list/<int:pk>/edit/', edit_contact_list, name='edit_contact_list'),
    # path('cl/list/<int:pk>/delete/', delete_contact_list, name='delete_contact_list'),

    path('email-templates/', email_template_list, name='email_template_list'),
    path('email-templates/create/', email_template_new, name='email_template_new'),
    path('email-templates/<int:pk>/edit/', email_template_edit, name='email_template_edit'),
    path('email-templates/<int:pk>/detail/', email_template_detail, name='email_template_detail'),
    path('email-templates/<int:pk>/delete/', email_template_delete, name='email_template_delete'),

    path('campaigns/', campaign_list, name='campaign_list'),
    path('campaigns/create/', campaign_new, name='campaign_new'),
    # path('cm/<int:pk>/edit/', campaign_edit, name='campaign_edit'),
    path('campaigns/<int:pk>/details/', campaign_details, name='campaign_details'),
    path('campaigns/<int:pk>/delete/', campaign_delete, name='campaign_delete'),
    path('cm/link/<int:link_id>/e/<int:email_id>/', campaign_link_click, name='campaign_link_click'),
    path('cm/track-email/<int:campaign_log_id>/contact/<int:email_id>/', campaign_open, name='campaign_open'),
    path('demo-file-download-for-contacts-list/', demo_file_download, name='demo_file_download'),
    path('unsubscribe-from-campaign/<int:contact_id>/<int:campaign_id>/', unsubscribe_from_campaign, name="unsubscribe_from_campaign"),
    path('contacts/<int:contact_id>/view/', contact_detail, name="contact_detail"),
    path('download-contacts-for-campaign/<int:compaign_id>/', download_contacts_for_campaign, name="download_contacts_for_campaign"),
    path('create-campaign-from-template/<int:template_id>/', create_campaign_from_template, name="create_campaign_from_template"),
    path('download-links-clicked/<int:campaign_id>/', download_links_clicked, name="download_links_clicked"),
    path('delete_multiple_contacts/', delete_multiple_contacts, name="delete_multiple_contacts"),
    path('download-failed-contacts/<int:contact_list_id>/', download_failed_contacts, name="download_failed_contacts"),
    path('delete_all_contacts/<int:contact_list_id>/', delete_all_contacts, name="delete_all_contacts"),
    path('add-email-for-campaigns/', add_email_for_campaigns, name="add_email_for_campaigns"),
    path('list-all-emails-for-campaigns/', list_all_emails_for_campaigns, name="list_all_emails_for_campaigns"),
    path('edit-email-for-campaigns/<int:pk>/', edit_email_for_campaigns, name="edit_email_for_campaigns"),
    path('delete-email-for-campaigns/<int:pk>/', delete_email_for_campaigns, name="delete_email_for_campaigns"),

    path('add-blocked-domain/', add_blocked_domain, name="add_blocked_domain"),
    path('blocked-domain-list/', blocked_domain_list, name="blocked_domain_list"),
    path('edit-blocked-domain/<int:blocked_domain_id>/', edit_blocked_domain, name="edit_blocked_domain"),
    path('delete-blocked-domain/<int:blocked_domain_id>/', delete_blocked_domain, name="delete_blocked_domain"),

    path('add-blocked-email/', add_blocked_email, name="add_blocked_email"),
    path('blocked-email-list/', blocked_email_list, name="blocked_email_list"),
    path('edit-blocked-email/<int:blocked_email_id>/', edit_blocked_email, name="edit_blocked_email"),
    path('delete-blocked-email/<int:blocked_email_id>/', delete_blocked_email, name="delete_blocked_email"),

    path('search-marketing-contact-emails/', include('haystack.urls')),
    # path('elastic-search/', contacts_list_elastic_search),
]

tasks/urls.py
from django.urls import path
from tasks.views import *

app_name = 'tasks'


urlpatterns = [
    path('', tasks_list, name='tasks_list'),
    path('create/', task_create, name='task_create'),
    path('detail/<int:task_id>/', task_detail, name='task_detail'),
    path('edit/<int:task_id>/', task_edit, name='task_edit'),
    path('delete/<int:task_id>/', task_delete, name='task_delete'),

    path('comment/add/', AddCommentView.as_view(), name="add_comment"),
    path('comment/edit/', UpdateCommentView.as_view(), name="edit_comment"),
    path('comment/remove/', DeleteCommentView.as_view(), name="remove_comment"),

    path('attachment/add/', AddAttachmentView.as_view(), name="add_attachment"),
    path('attachment/remove/', DeleteAttachmentsView.as_view(),
         name="remove_attachment"),
]

templates/marketing/base.html
{% extends 'root.html' %}

{% block main_menu %}
<ul class="navbar-nav mr-auto">
  <!-- add submenu for contacts-->
  {% if request.user.is_superuser or request.user.role == 'ADMIN' or request.user.has_marketing_access %}
  <li class="nav-item"><a class="nav-link" id="marketing-dashboard" href="{% url 'marketing:dashboard' %}">Dashboard</a>
  </li>
  <li class="nav-item mt-2 contact_class" id="contact">
    <div class="btn-group">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false" style="box-shadow: none; color: #657b88">
        Contacts
      </button>
      <div class="dropdown-menu mt-2">
        <a class="dropdown-item contact-list" id="contact-list" href="{% url 'marketing:contact_lists' %}">Contacts
          List</a>
        <!-- <div class="dropdown-divider"></div> -->
        <a class="dropdown-item contacts" id="contacts" href="{% url 'marketing:contacts_list' %}">Contacts</a>
        <!-- <a class="dropdown-item contacts" id="contacts" href="/marketing/search-marketing-contact-emails/">Search Contacts</a> -->
      </div>
    </div>
  </li>

  <!-- <li class="nav-item"><a href="{% url 'marketing:contact_lists' %}" class="nav-link" id="contact_lists">Contacts</a>
  </li> -->
  <li class="nav-item"><a class="nav-link" id="email-templates" href="{% url 'marketing:email_template_list' %}">Email
      templates</a></li>
  <li class="nav-item"><a class="nav-link" id="campaigns" href="{% url 'marketing:campaign_list' %}">Campaigns</a></li>
  {% endif %}
  <!-- <li class="nav-item"><a class="nav-link" id="leads" href="{% url 'leads:list' %}">Leads</a></li>
  <li class="nav-item"><a class="nav-link" id="opportunities"href="{% url 'opportunities:list' %}">Opportunities</a></li>
  <li class="nav-item"><a class="nav-link" id="cases" href="{% url 'cases:list' %}">Cases</a></li>
  <li class="nav-item"><a class="nav-link" id="documents" href="{% url 'common:doc_list' %}">Documents</a></li>
  <li class="nav-item"><a class="nav-link" id="tasks" href="{% url 'tasks:tasks_list' %}">Tasks</a></li>
  <li class="nav-item"><a class="nav-link" id="invoices" href="{% url 'invoices:invoices_list' %}">Invoices</a></li>
  <li class="nav-item"><a class="nav-link" id="events" href="{% url 'events:events_list' %}">Events</a></li> -->
</ul>
{% endblock %}



{% comment %}


{% extends 'root.html' %}
{% load staticfiles %}
{% load compress %}
{% load thumbnail %}
{% block main_menu %}
<!-- <ul class="navbar-nav mr-auto">
</ul> -->
{% endblock %}
{% block header %}

{% endblock header %}


{% block content %}
<div class="side_menu">
  <!-- <div class="logo_block"> -->
  <!-- <a href="#">Django <span class="green_color text-uppercase">Crm</span></a> -->
  <div class="dropdown">
    <a class="dropdown-toggle navbar-brand mt-2 ml-3" href="#" role="button" id="dropdownMenuLink"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
      style="color:#000; font-weight: 800; font-size: 1.5em;">
      Django <span class="green_color text-uppercase" style="color:#7ae847">Crm</span>
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="/">Sales</a>
      <a class="dropdown-item" href="{% url 'marketing:dashboard' %}">Marketing</a>
    </div>
  </div>
  <!-- </div> -->
  <div class="profile_block">
    <ul>

      <li data-toggle="tooltip" data-placement="bottom" title="{{request.user}}">
        <a href="#" class="profile_pic">
          <!-- <img src="https://lh3.googleusercontent.com/-6gBVCn2WaAk/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rd7EWo94Fj0ep0DQa3tDjddczFC3g/s96-c-mo/photo.jpg" alt="profile picture"> -->
          {% if not request.user.profile_pic %}
          <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
          {% else %}
          {% thumbnail request.user.profile_pic "25x25" as im %}
          <img src="{{ im.url }}">
          {% endthumbnail %}
          {% endif %}
        </a>
      </li>

      <li data-toggle="tooltip" data-placement="bottom" title="Users">
        <a href="{% url 'common:users_list' %}" class="sky_blue box"><i class="fas fa-users"></i>
        </a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Change Password">
        <a href="{% url 'common:change_password' %}" class="red box"><i class="fas fa-key"></i></a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Profile">
        <a href="{% url 'common:profile' %}" class="green box"><i class="fas fa-user"></i></a>
      </li>
      <li data-toggle="tooltip" data-placement="bottom" title="Logout">
        <a href="{% url 'common:logout' %}" class="purple box"><i class="fas fa-sign-out-alt"></i></a>
      </li>
    </ul>
  </div>
  <div class="menu_block">
    <ul class="main_menu">
      <li class="parent_menu">
        <a href="{% url 'marketing:contact_lists' %}" class="red"><i class="far fa-address-book"></i>Contacts</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:contacts_list' %}" class="yellow"><i class="fas fa-bars"></i>All Contacts</a>
          </li>
          <li><a href="{% url 'marketing:contact_list_new' %}" class="yellow"><i class="far fa-plus-square"></i>Create
              Contact</a></li>
        </ul>
      </li>
      <li class="parent_menu">
        <a href="{% url 'marketing:email_template_list' %}" class="purple"><i class="fas fa-envelope-open"></i>Email
          Templates</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:email_template_list' %}" class="d_green"><i class="fas fa-bars"></i>All
              Templates</a></li>
          <li><a href="{% url 'marketing:email_template_new' %}" class="d_green"><i
                class="far fa-plus-square"></i>Create
              Template</a></li>
        </ul>
      </li>
      <li class="parent_menu">
        <a href="{% url 'marketing:campaign_list' %}" class="green"><i class="fas fa-at"></i>Campaigns</a>
        <ul class="submenu">
          <li><a href="{% url 'marketing:campaign_list' %}" class="sky_color"><i class="fas fa-bars"></i>All
              Campaigns</a></li>
          <li><a href="{% url 'marketing:campaign_new' %}" class="sky_color"><i class="far fa-plus-square"></i>Create
              Campaign</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
<!-- <ul class="list-group side_menu mb-3">
  <li class="logo list-group-item">
    <div class="item">
      <a href="#">Django <span class="green_color text-uppercase">Crm</span></a>
    </div>
  </li>
  
  <li class="list-group-item d-flex justify-content-between">
    <div class="item">
      <h6 class="heading"><i class="fas fa-address-book"></i> Contacts</h6>
      <ul>
        <li><a href="/m/cl/all"><i class="fas fa-bars"></i>All</a></li>
        <li><a href="/m/cl/lists/" class=""><i class="fas fa-bars"></i> Lists</a></li>
        <li><a href="/m/cl/list/cnew/"> <i class="fas fa-plus"></i>Create New Contacts</a></li>
      </ul>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between">
    <div class="item">
      <h6 class="heading"><i class="fas fa-envelope"></i> Email Templates </h6>
      <ul>
        <li><a href="/m/et/list"><i class="fas fa-bars"></i>List</a></li>
        <li><a href="/m/et/new/"><i class="fas fa-plus"></i>Create New Template</a></li>
      </ul>
    </div>
  </li>
  <li class="list-group-item d-flex justify-content-between">
    <div class="item">
      <h6 class="heading"><i class="fas fa-bullhorn"></i> Campigns</h6>
      <ul>
        <li><a href="/m/cm/list/"><i class="fas fa-bars"></i>List</a></li>
        <li><a href="/m/cm/new/"><i class="fas fa-plus"></i>New Campaign</a></li>
      </ul>
    </div>
  </li>
</ul> -->
{% endblock %}

{% endcomment %}