common/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from common.views import (
    HomeView, LoginView, ForgotPasswordView, LogoutView,
    ChangePasswordView, ProfileView,
    UsersListView, CreateUserView, UpdateUserView, UserDetailView,
    UserDeleteView, PasswordResetView,
    DocumentListView, document_create, document_update,
    DocumentDetailView, DocumentDeleteView,
    download_document, change_user_status, download_attachment,
    add_comment, edit_comment, remove_comment,
    api_settings, add_api_settings, view_api_settings,
    update_api_settings, delete_api_settings,
    change_passsword_by_admin, google_login, create_lead_from_site,
    activate_user, resend_activation_link
)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'common'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgot-password/',
         ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/',
         ChangePasswordView.as_view(), name='change_password'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # User views
    path('users/list/', UsersListView.as_view(), name='users_list'),
    path('users/create/', CreateUserView.as_view(), name='create_user'),
    path('users/<int:pk>/edit/', UpdateUserView.as_view(), name="edit_user"),
    path('users/<int:pk>/view/', UserDetailView.as_view(), name='view_user'),
    path('users/<int:pk>/delete/',
         UserDeleteView.as_view(), name='remove_user'),

    path(
        'password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # Document
    path('documents/', DocumentListView.as_view(), name='doc_list'),
    path('documents/create/', document_create, name='create_doc'),
    path('documents/<int:pk>/edit/', document_update, name="edit_doc"),
    path('documents/<int:pk>/view/',
         DocumentDetailView.as_view(), name='view_doc'),
    path('documents/<int:pk>/delete/',
         DocumentDeleteView.as_view(), name='remove_doc'),

    # download
    path('documents/<int:pk>/download/',
         download_document, name='download_document'),

    # download_attachment
    path('attachments/<int:pk>/download/',
         download_attachment, name='download_attachment'),

    path('user/status/<int:pk>/',
         change_user_status, name='change_user_status'),

    path('comment/add/', add_comment, name="add_comment"),
    path('comment/<int:pk>/edit/', edit_comment, name="edit_comment"),
    path('comment/remove/', remove_comment, name="remove_comment"),

    # settings
    path('api/settings/', api_settings, name="api_settings"),
    path('api/settings/add/', add_api_settings, name="add_api_settings"),
    path('api/settings/<int:pk>/',
         view_api_settings, name="view_api_settings"),
    path('api/settings/<int:pk>/update/',
         update_api_settings, name="update_api_settings"),
    path('api/settings/<int:pk>/delete/',
         delete_api_settings, name="delete_api_settings"),

    path('change-password-by-admin/', change_passsword_by_admin,
         name="change_passsword_by_admin"),
    path('google/login/', google_login, name="google_login"),
    path('create-lead-from-site/', create_lead_from_site,
         name='create_lead_from_site'),

    # user activate link
    path('activate-user/<uidb64>/<token>/<activation_key>/', activate_user, name='activate_user'),
    path('resend_activation_link/<userId>/', resend_activation_link, name='resend_activation_link'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = 'crm'

urlpatterns = [
    path('', include('common.urls', namespace="common")),
    path('', include('django.contrib.auth.urls')),
    path('marketing/', include('marketing.urls', namespace="marketing")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('leads/', include('leads.urls', namespace="leads")),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('opportunities/',
         include('opportunity.urls', namespace="opportunities")),
    path('cases/', include('cases.urls', namespace="cases")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('invoices/', include('invoices.urls', namespace="invoices")),
    path('events/', include('events.urls', namespace="events")),
    path('teams/', include('teams.urls', namespace="teams")),
    path('emails/', include('emails.urls', namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path('logout/', views.LogoutView, {'next_page': '/login/'}, name="logout"),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = handler404
handler500 = handler500

teams/urls.py
from django.urls import path
from teams.views import (
    teams_list, team_create, team_edit, team_delete, team_detail
)


app_name = 'teams'


urlpatterns = [
    path('', teams_list, name='teams_list'),
    path('create/', team_create, name='team_create'),
    path('edit/<int:team_id>/', team_edit, name='team_edit'),
    path('delete/<int:team_id>/', team_delete, name='team_delete'),
    path('detail/<int:team_id>/', team_detail, name='team_detail'),

]

cases/models.py
import arrow
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from accounts.models import Account
from contacts.models import Contact
from common.models import User
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE
from planner.models import Event
from teams.models import Teams


class Case(models.Model):
    name = models.CharField(
        pgettext_lazy("Name of the case", "Name"),
        max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(
        choices=CASE_TYPE, max_length=255, blank=True, null=True, default='')
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    # closed_on = models.DateTimeField()
    closed_on = models.DateField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(
        User, related_name='case_assigned_users')
    created_by = models.ForeignKey(
        User, related_name='case_created_by',
        on_delete=models.SET_NULL, null=True)
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    teams = models.ManyToManyField(Teams, related_name='cases_teams')


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.name

    @property
    def get_team_users(self):
        team_user_ids = list(self.teams.values_list('users__id', flat=True))
        return User.objects.filter(id__in=team_user_ids)

    @property
    def get_team_and_assigned_users(self):
        team_user_ids = list(self.teams.values_list('users__id', flat=True))
        assigned_user_ids = list(self.assigned_to.values_list('id', flat=True))
        user_ids = team_user_ids + assigned_user_ids
        return User.objects.filter(id__in=user_ids)

    @property
    def get_assigned_users_not_in_teams(self):
        team_user_ids = list(self.teams.values_list('users__id', flat=True))
        assigned_user_ids = list(self.assigned_to.values_list('id', flat=True))
        user_ids = set(assigned_user_ids) - set(team_user_ids)
        return User.objects.filter(id__in=list(user_ids))

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Meeting",
            status="Planned")

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Meeting").exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type,
                                    object_id=self.id,
                                    event_type="Task",
                                    status="Planned")

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Task").exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(content_type=content_type,
                                    object_id=self.id, event_type="Call",
                                    status="Planned")

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Call").exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

teams/models.py
import arrow

from django.db import models
from common.models import User
from django.utils.translation import ugettext_lazy as _


class Teams(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    users = models.ManyToManyField(User, related_name='user_teams')
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name='teams_created', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

    def get_users(self):
        return ','.join([str(_id) for _id in list(self.users.values_list('id', flat=True))])
        # return ','.join(list(self.users.values_list('id', flat=True)))

teams/forms.py
from django import forms
from teams.models import Teams
from common.models import User


class TeamForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TeamForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}

        self.fields['name'].required = True
        self.fields['description'].required = False
        self.fields['users'].required = True
        self.fields['users'].queryset = User.objects.filter(is_active=True)

    class Meta:
        model = Teams
        fields = ('name', 'description', 'users',)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Teams.objects.filter(name__iexact=name).exclude(id=self.instance.id).exists():
            raise forms.ValidationError('Team with this name already exists.')
        return name

teams/views.py
from datetime import date, datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  TemplateView, UpdateView, View)

from common.models import User
from teams.models import Teams
from teams.forms import TeamForm
from teams.tasks import update_team_users


@login_required
def teams_list(request):
    context = {}
    if request.user.role == 'ADMIN' or request.user.is_superuser:
        queryset = Teams.objects.all()
        users = User.objects.all()
        context['teams'] = queryset
        context['users'] = users
    else:
        raise PermissionDenied

    if request.method == 'GET':
        user_ids = list(queryset.values_list('created_by', flat=True))
        user_ids.append(request.user.id)
        context['created_by_users'] = users.filter(is_active=True, id__in=user_ids)
        return render(request, 'teams.html', context)
    if request.method == 'POST':
        if request.POST.get('team_name'):
            queryset = queryset.filter(
                name__icontains=request.POST.get('team_name'))
        if request.POST.get('created_by'):
            queryset = queryset.filter(
                created_by=request.POST.get('created_by'))
        if request.POST.get('assigned_to'):
            queryset = queryset.filter(
                users__id__in=request.POST.getlist('assigned_to'))
        context['assigned_to'] = request.POST.getlist('assigned_to')
        context['teams'] = queryset
        user_ids = list(queryset.values_list('created_by', flat=True))
        user_ids.append(request.user.id)
        context['created_by_users'] = users.filter(is_active=True, id__in=user_ids)
        return render(request, 'teams.html', context)


@login_required
def team_create(request):
    context = {}
    if request.user.role == 'ADMIN' or request.user.is_superuser:
        teams = Teams.objects.all()
        context['teams'] = teams
    else:
        raise PermissionDenied

    if request.method == 'GET':
        form = TeamForm()
        context['form'] = TeamForm()
        return render(request, 'team_create.html', context)

    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            task_obj = form.save(commit=False)
            task_obj.created_by=request.user
            task_obj.save()
            form.save_m2m()
            return JsonResponse({'error': False, 'success_url': reverse('teams:teams_list')})
        else:
            return JsonResponse({'error': True, 'errors': form.errors})


@login_required
def team_detail(request, team_id):
    if not (request.user.role == 'ADMIN' or request.user.is_superuser):
        raise PermissionDenied
    team_obj = get_object_or_404(Teams, pk=team_id)
    context = {}

    if request.method == 'GET':
        context['team_obj'] = team_obj
        return render(request, 'team_detail.html', context)


@login_required
def team_edit(request, team_id):
    if not (request.user.role == 'ADMIN' or request.user.is_superuser):
        raise PermissionDenied
    team_obj = get_object_or_404(Teams, pk=team_id)
    context = {}

    if request.method == 'GET':
        form = TeamForm(instance=team_obj)
        context['form'] = form
        return render(request, 'team_create.html', context)

    if request.method == 'POST':
        form = TeamForm(request.POST, instance=team_obj)
        if form.is_valid():
            task_obj = form.save(commit=False)
            if 'users' in form.changed_data:
                update_team_users.delay(team_id)
                # pass
                # print('celery task')
            task_obj.save()
            form.save_m2m()
            return JsonResponse({'error': False, 'success_url': reverse('teams:teams_list')})
        else:
            return JsonResponse({'error': True, 'errors': form.errors})


@login_required
def team_delete(request, team_id):
    if not (request.user.role == 'ADMIN' or request.user.is_superuser):
        raise PermissionDenied
    team_obj = get_object_or_404(Teams, pk=team_id)
    context = {}

    if request.method == 'GET':
        team_obj.delete()
        return redirect('teams:teams_list')

teams/templates/team_create.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% block extralinks %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block breadcrumb %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'teams:teams_list' %}">Teams</a></li>
    <li class="breadcrumb-item">{% if team_obj %}Edit{% else %}Create{% endif %}</li>
  </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
<form id="add_form" method="POST" action="" novalidate>
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="card-title text-center">
            {% if team_obj %}EDIT{% else %}CREATE{% endif %} TEAM
          </div>
          <div class="row marl">
            <div class="col-md-12">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_firstname">Name {% if form.name.field.required %}<span class="error_marker"
                      style="color:red">*</span>{% endif %}</label>
                  {{form.name}}
                </div>
                <span class="error" id="id__name"></span>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_firstname">Description {% if form.description.field.required %}<span
                      class="error_marker" style="color:red">*</span>{% endif %}</label>
                  {{form.description}}
                </div>
                <span class="error" id="id__description"></span>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label for="id_firstname">Assign Users {% if form.users.field.required %}<span class="error_marker"
                      style="color:red">*</span>{% endif %}</label>
                  {{form.users}}
                </div>
                <span class="error" id="id__users"></span>
              </div>
            </div>
          </div>
          <div class="row marl buttons_row form_btn_row text-center">
            <button class="btn btn-default save" type="submit" id="submit_btn">Save</button>
            <a href="{% url 'teams:teams_list' %}" class="btn btn-default clear" id="create_doc_cancel">Cancel</a>

          </div>

        </div>
      </div>
    </div>
  </div>
</form>


{% endblock content %}
{% block js_block %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://malsup.github.io/jquery.form.js"></script>
<script type="text/javascript">

  $(document).ready(function () {
    $('#id_users').select2();
  });


  $('form#add_form').ajaxForm({
    type: 'POST',
    dataType: 'json',
    url: ".",
    data: $('#add_form').serialize(),
    beforeSubmit: disableButton,
    success: function (data) {
      if (data.error) {
        $('.error').html('')
        for (var key in data.errors) {
          $('#id__' + key).html("<p>" + data.errors[key][0] + "</p>");
        };
        $('#submit_btn').removeAttr('disabled')
      }
      else {
        window.location = data.success_url;
      }
    }
  });


  function disableButton() {
    // $('#progress_bar').show()
    $('#submit_btn').attr('disabled', 'disabled')
  }

</script>
{% endblock js_block %}

teams/templates/team_detail.html
{% extends 'sales/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'teams:teams_list' %}">Teams</a></li>
    <li class="breadcrumb-item" active>View</li>
  </ol>
</nav>
<!-- OPPORTUNITY VIEW STARTS -->
<div class="main_container" id="maincontainer">
  <div class="overview_form_block row marl justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body" id="datashow">
          <div class="panel-heading card-title view-pad text-center">
            <h5>
              Team
            </h5>
            <a href="{% url 'teams:team_edit' team_obj.id %}" class="btn btn-success edit">Edit</a>
          </div>
          <div class="row marl no-gutters">
            <div class="col-md-8">
              {% if team_obj.name %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_title" data-name="title">Name</label>
                  <div class="contact_field" id="doc_title" data-name="name">{{ team_obj.name }}
                  </div>
                </div>
              </div>
              {% endif %}
              {% if team_obj.description %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_status" data-name="status">Description</label>
                  <div class="contact_field" id="doc_status" data-name="status">
                    {{ team_obj.description }} </div>
                </div>
              </div>
              {% endif %}
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="contact_field_label" for="id_status" data-name="status">Assigned To</label>
                  <br>
                  {% with users=team_obj.users.all %}
                  {% for user in users %}
                  {% if user.profile_pic %}
                  {% thumbnail user.profile_pic "40x40" crop="center" as im %}
                  <span>
                    <a href="{% url 'common:view_user' user.id %}">
                      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" title="{{ user.email }}">
                    </a>
                  </span>
                  {% endthumbnail %}
                  {% else %}
                  <span>
                    <a href="{% url 'common:view_user' user.id %}">
                      <img src="{% static 'images/user.png' %}" title="{{ user.email }}" width="40" height="40">
                    </a>
                  </span>
                  {% endif %}
                  {% empty %}
                  None
                </div>
              </div>
              {% endfor %}
              {% endwith %}
              <div class="filter_col col-md-12" style="padding: 0;">
                <div class="form-group mt-3">
                  <label class="contact_field_label" for="id_created_by" data-name="created_by">Created By</label>
                  <div class="contact_field" id="created_by" data-name="created_by">
                    {{ team_obj.created_by }}</div>
                </div>
              </div>
              <div class="filter_col col-md-12" style="padding: 0;">
                <div class="form-group">
                  <label class="contact_field_label" for="id_created_on" data-name="created_on">Created On</label>
                  <div class="contact_field" id="created_on" data-name="created_on" title="{{ team_obj.created_on }}">
                    {{ team_obj.created_on_arrow }}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}